{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homehelper-api.fullname" . }}-secrets
  labels:
    {{- include "homehelper-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }} 